import { PageHero, Section } from "@/components/Section";
import Seo, { breadcrumbSchema, orgSchema } from "@/components/Seo";
import Breadcrumbs from "@/components/Breadcrumbs";
import { FileDown } from "lucide-react";
import whitePaperAsset from "@/assets/documents/atpd-2352-rev-u-sensor-white-paper.pdf.asset.json";

const crumbs = [
  { name: "Home", path: "/" },
  { name: "Engineering Resources", path: "/engineering-resources" },
  { name: "White Paper", path: "/white-papers/atpd-2352-rev-u-sensor" },
];

const WhitePaperAtpd2352 = () => (
  <>
    <Seo
      title="ATPD-2352 Rev U White Paper — Embedded Temperature Sensing for Heated Transparent Armor | HLG"
      description="Technical white paper on preserving ATPD-2352 Revision U durability gains through embedded laminate temperature sensing and closed-loop heater control in heated transparent armor systems."
      path="/white-papers/atpd-2352-rev-u-sensor"
      schema={[orgSchema, breadcrumbSchema(crumbs)]}
    />
    <Breadcrumbs items={crumbs} />
    <PageHero
      eyebrow="Technical White Paper"
      title="Ensuring ATPD-2352 Revision U Durability Gains Are Preserved in Operational Service"
      subtitle="Embedded Laminate Temperature Sensing for Heated Transparent Armor Systems"
    />

    <Section>
      <div className="max-w-3xl mx-auto">
        <div className="panel p-8">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-border pb-6">
            <div>
              <div className="mono text-[10px] text-primary">Author</div>
              <div className="font-medium mt-1">D. Kent Hartley</div>
              <div className="text-sm text-muted-foreground">
                Technical Specialist – Transparent Armor, Heated Laminated Glazing, and Aerospace Glazing Systems
              </div>
            </div>
            <div className="text-left sm:text-right">
              <div className="mono text-[10px] text-primary">Date</div>
              <div className="font-medium mt-1">March 14, 2026</div>
            </div>
          </div>

          <div className="mt-8 space-y-6 text-muted-foreground leading-relaxed">
            <p>
              ATPD-2352 Revision U represents one of the most significant advances in durability qualification for transparent armor systems used on military ground vehicles. The updated specification incorporates expanded environmental conditioning and accelerated aging protocols designed to identify laminate instability mechanisms prior to field deployment.
            </p>
            <p>
              While qualification testing provides a critical framework for validating laminate durability, operational conditions encountered during field service may introduce additional stress mechanisms not directly controlled within the test environment. One of the most significant of these operational variables is thermal exposure generated by electrically heated windshield systems.
            </p>
            <p>
              Heated transparent armor windshields typically rely on conductive heating interlayers embedded within the laminate structure. In many currently fielded systems, heater output is regulated using open-loop electrical control, meaning heater power is applied without direct measurement of laminate temperature.
            </p>
            <p>
              When laminate temperature is not monitored, heaters may remain energized regardless of the actual thermal conditions within the glazing structure. Over extended operating periods, this can lead to cumulative thermal dwell exposure. Because laminated glazing materials exhibit strong time-temperature dependent behavior, prolonged exposure to elevated temperature can accelerate degradation mechanisms that ultimately lead to delamination or optical distortion.
            </p>
            <p>
              Embedding laminate temperature sensors within transparent armor laminates enables closed-loop heater control, allowing heater output to be automatically regulated based on actual laminate temperature. This approach ensures that operational thermal exposure remains within the durability envelope validated during ATPD-2352 Revision U testing.
            </p>
          </div>

          <div className="mt-10">
            <h2 className="font-display text-2xl font-bold">What this paper covers</h2>
            <ul className="mt-4 space-y-3 text-muted-foreground">
              <li className="flex gap-3">
                <span className="text-primary">01</span>
                <span>The ATPD-2352 Revision U durability framework and why it matters for lifecycle performance.</span>
              </li>
              <li className="flex gap-3">
                <span className="text-primary">02</span>
                <span>How open-loop heater control creates cumulative thermal dwell exposure in transparent armor laminates.</span>
              </li>
              <li className="flex gap-3">
                <span className="text-primary">03</span>
                <span>Time-temperature behavior of polymer interlayers and the heater-driven delamination mechanisms it enables.</span>
              </li>
              <li className="flex gap-3">
                <span className="text-primary">04</span>
                <span>Cross-industry thermal control practices from aerospace, marine, rail, and commercial transportation.</span>
              </li>
              <li className="flex gap-3">
                <span className="text-primary">05</span>
                <span>A practical sensor integration architecture for closed-loop heater control in heated transparent armor systems.</span>
              </li>
              <li className="flex gap-3">
                <span className="text-primary">06</span>
                <span>Fleet sustainment impact and why embedded temperature sensing is an inexpensive insurance policy for Rev U durability gains.</span>
              </li>
            </ul>
          </div>

          <div className="mt-10 pt-8 border-t border-border">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div>
                <div className="font-display text-lg font-semibold">Download the full paper</div>
                <p className="text-sm text-muted-foreground mt-1">
                  16 pages · PDF · 138 KB
                </p>
              </div>
              <a
                href={whitePaperAsset.url}
                download
                className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-5 py-2.5 rounded-md font-medium text-sm hover:bg-primary/90 transition-colors"
              >
                <FileDown size={16} /> Download PDF
              </a>
            </div>
          </div>
        </div>
      </div>
    </Section>
  </>
);

export default WhitePaperAtpd2352;
