// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-technologies.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/data/hlg.ts
var technologies = [
  {
    code: "HEAT",
    slug: "electrically-heated-interlayers",
    name: "Electrically Heated Interlayers",
    cardCopy: "Fine-wire and transparent-conductor heating systems engineered around voltage, power density, geometry and thermal requirements.",
    h1: "Electrically heated interlayers",
    lead: "HLG engineers fine-wire and transparent-conductor heating systems for laminated glass. The heater is engineered around the electrical requirement \u2014 not adapted from a catalog part.",
    sections: [
      {
        title: "Engineered around the electrical requirement",
        body: "Heater architecture follows from the supply voltage, the power or thermal objective, the transparency geometry and the electrical interface available in the assembly.",
        bullets: [
          "Conductor architecture and wire selection",
          "Resistance and power distribution",
          "Busbar geometry and collection",
          "Lead routing and electrical exits",
          "Laminate stack compatibility"
        ]
      },
      {
        title: "Conductor formats",
        bullets: [
          "Embedded fine tungsten wire",
          "Transparent conductive coatings and films",
          "Fine conductive mesh architectures"
        ]
      },
      {
        title: "Validation",
        bullets: [
          "Electrical resistance and continuity verification",
          "Thermal imaging of new heater designs",
          "Temperature uniformity evaluation",
          "Optical evaluation while energized after prototype lamination, where required"
        ]
      }
    ],
    specs: [
      { label: "Voltage capability", value: "12\u2013480 V" },
      { label: "Power density", value: "approx. 0.05\u20135.0 W/in\xB2" },
      { label: "Tungsten capability", value: "14\u201361 \xB5m" },
      { label: "Demonstrated production spacing", value: "0.5 mm" },
      { label: "Inspection", value: "100% of HLG-fabricated interlayers" }
    ],
    closing: "Your glass. Your electrical requirements. HLG engineers the heater.",
    seoTitle: "Electrically Heated Interlayers for Laminated Glass | HLG",
    seoDescription: "HLG engineers electrically heated interlayers for laminated glass: fine tungsten wire and transparent conductor heating from 12\u2013480 V, approx. 0.05\u20135.0 W/in\xB2, busbars and electrical exits."
  },
  {
    code: "SENSE",
    slug: "embedded-temperature-sensing",
    name: "Embedded Temperature Sensing",
    cardCopy: "A growth technology for HLG: thin RTD sensing wire embedded within the interlayer for temperature feedback, control and over-temperature protection.",
    h1: "The sensor is required. How it is integrated matters.",
    lead: "HLG designs and manufactures thin RTD sensor interlayers for heated transparencies. Sensor placement, lead routing and electrical exits are engineered as part of the laminate architecture rather than treated as unrelated components.",
    sections: [
      {
        title: "Embedded within the interlayer",
        body: "Unlike RTDs placed on top of an interlayer, HLG integrates the fine sensing wire within a dedicated interlayer. The sensor location, conductor path and lead routing become part of the laminate architecture."
      },
      {
        title: "What the sensor interlayer does",
        bullets: [
          "RTD placement at the locations that matter thermally",
          "Temperature feedback to the control system",
          "Over-temperature protection",
          "Multiple sensing locations where the application requires them"
        ]
      },
      {
        title: "Integration engineering",
        body: "A sensing element only performs as well as the way it reaches the outside of the laminate.",
        bullets: [
          "Sensor lead routing inside the stack",
          "Electrical exits and edge transitions",
          "Interaction between sensor mat and heater architecture",
          "Prelamination of the sensor interlayer where appropriate"
        ]
      },
      {
        title: "Matched heater + sensor systems",
        body: "HLG can produce the heater mat and a dedicated RTD sensor mat as a matched electrical and thermal system, engineered together, with validation after lamination."
      }
    ],
    closing: "HLG has production aerospace heater and matching sensor-mat experience.",
    cta: { label: "Start a heater + sensor integration review", to: "/engineering-review" },
    seoTitle: "Embedded RTD Temperature Sensing Interlayers | HLG",
    seoDescription: "HLG designs thin RTD sensor interlayers for heated transparencies: sensor placement, multiple sensing locations, lead routing, electrical exits and matched heater + sensor systems."
  },
  {
    code: "SHIELD",
    slug: "emi-rfi-shielding",
    name: "EMI/RFI Shielding",
    cardCopy: "Conductive interlayer architectures engineered around the complete electrical path from transparent shielding layer through perimeter collection and grounding.",
    h1: "EMI/RFI shielding is an electrical system, not simply a conductive piece of glass",
    lead: "The shielding layer is one element in a path. HLG engineers the conductive interlayer together with how current is collected at the perimeter and how it leaves the assembly.",
    sections: [
      {
        title: "The electrical path",
        body: "Conductive layer \u2192 perimeter collection \u2192 electrical exit / ground \u2192 frame \u2192 enclosure. A discontinuity anywhere in that path governs the result."
      },
      {
        title: "What HLG engineers",
        bullets: [
          "Transparent shielding layer selection \u2014 fine mesh or conductive coating",
          "Perimeter collection geometry",
          "Grounding interface and electrical exit",
          "Laminate stack and edge treatment",
          "Manufacturing controls and inspection"
        ]
      },
      {
        title: "V1 disclosure",
        body: "Specific shielding attenuation values and compliance statements are program- and construction-dependent and are not published here. HLG discusses shielding performance under a mutual NDA in the context of a defined assembly."
      }
    ],
    seoTitle: "EMI/RFI Shielding Interlayers for Laminated Glass | HLG",
    seoDescription: "HLG engineers EMI/RFI shielding interlayers as a complete electrical system: transparent conductive layer, perimeter collection, grounding interface and electrical exits."
  },
  {
    code: "CONDUCT",
    slug: "transparent-conductive-films",
    name: "Transparent Conductors",
    cardCopy: "Embedded fine wire, conductive coatings, transparent films and mesh architectures selected around the required electrical and optical function.",
    h1: "Select the conductor around the function",
    lead: "No single transparent conductor is best for every application. Sheet resistance, optical requirements, geometry, current density and laminate compatibility all move the answer.",
    sections: [
      {
        title: "Embedded fine wire",
        body: "Mature, demonstrated HLG capability. Very fine tungsten conductors placed to a controlled geometry \u2014 high current capability with minimal optical footprint."
      },
      {
        title: "Conductive film (ITO and conductive coatings)",
        body: "Mature capability. A continuous transparent conductive film \u2014 ITO and related coatings \u2014 for uniform area conduction and heating with no discrete conductor lines; sheet resistance governs achievable power."
      },
      {
        title: "Fine conductive mesh",
        body: "Mature capability. Useful where area conduction and shielding continuity are both required."
      },
      {
        title: "AgNW and emerging conductors",
        body: "Development stage. HLG evaluates silver nanowire and other emerging conductor systems on a development basis. These are not presented as mature HLG production capability."
      }
    ],
    seoTitle: "Transparent Conductors for Laminated Glass \u2014 Wire, ITO, Mesh | HLG",
    seoDescription: "Embedded fine wire, ITO and conductive coatings, fine conductive mesh and emerging conductors \u2014 HLG selects the transparent conductor around the electrical and optical function."
  },
  {
    code: "SWITCH",
    slug: "switchable-smart-glazing",
    name: "Switchable Glazing",
    cardCopy: "Integration of PDLC and other electrically controlled glazing technologies into laminate-ready assemblies.",
    h1: "Switchable glazing is a system, not simply a sheet of film",
    lead: "HLG focuses on integrating PDLC and other electrically controlled glazing technologies into laminate-ready assemblies, with the electrical interface engineered for the finished construction.",
    sections: [
      {
        title: "What HLG engineers",
        bullets: [
          "Film integration into the laminate stack",
          "Electrical interface, bus geometry and exits",
          "Edge treatment and perimeter detailing",
          "Alignment and dimensional control before lamination",
          "Manufacturing controls and inspection"
        ]
      },
      {
        title: "Technology-neutral",
        body: "HLG works with the switchable technology appropriate to the program. Electrochromic systems are not presented as mature HLG production capability."
      }
    ],
    seoTitle: "PDLC & Switchable Glazing Integration for Laminates | HLG",
    seoDescription: "HLG integrates PDLC and electrically controlled glazing into laminate-ready assemblies \u2014 film integration, electrical interfaces, bus geometry, exits and manufacturing controls."
  },
  {
    code: "CONNECT",
    slug: "integrated-antennas-laminated-glass",
    name: "Integrated Antennas",
    cardCopy: "Fine-wire and transparent-conductor antenna architectures engineered for reliable integration into laminated glass.",
    h1: "The RF engineer designs the antenna. HLG engineers how it becomes glass.",
    lead: "The customer or their RF specialist defines the antenna geometry and RF target. HLG translates that design into a manufacturable laminated-glass interlayer using transparent conductive film or embedded fine wire.",
    sections: [
      {
        title: "What HLG engineers",
        bullets: [
          "Conductor integration and placement accuracy",
          "Feed architecture",
          "Electrical exits and connector interface",
          "Laminate stack-up",
          "Manufacturing controls and inspection"
        ]
      },
      {
        title: "Scope",
        body: "HLG does not present itself as performing full RF antenna design unless specifically responsible for it in a program. The division of responsibility is defined at the start of an engineering review."
      }
    ],
    seoTitle: "Integrated Antennas in Laminated Glass | HLG",
    seoDescription: "HLG turns antenna geometry into a manufacturable laminated-glass interlayer using fine wire or transparent conductive film \u2014 conductor integration, feed architecture and electrical exits."
  }
];
var getTech = (slug) => technologies.find((t) => t.slug === slug);
var solutions = [
  {
    id: "functional-interlayer-integration",
    name: "Functional Interlayer Integration",
    body: "HLG combines electrical technologies into engineered, laminate-ready functional interlayer assemblies. The glass laminator laminates the glass; HLG integrates the function.",
    bullets: [
      "HEAT + SENSE \u2014 heating with integrated temperature feedback",
      "HEAT + CONDUCT \u2014 fine-wire or transparent-conductor heating architectures",
      "SHIELD + GROUND \u2014 transparent shielding with engineered perimeter collection and electrical exit",
      "CONNECT + CONDUCT \u2014 antenna geometry translated into a manufacturable interlayer",
      "SWITCH + CONNECT \u2014 electrical interfaces engineered around switchable glazing systems"
    ]
  },
  {
    id: "prelaminated-functional-assemblies",
    name: "Prelaminated Functional Assemblies",
    body: "Where appropriate, HLG can preintegrate multiple interlayer components before they reach the glass laminator \u2014 controlling alignment, electrical interfaces, conductor placement and exits.",
    bullets: [
      "Alignment control between functional layers",
      "Electrical interfaces established before lamination",
      "Conductor placement verified in-process",
      "Fewer variables introduced at the glass laminator"
    ]
  },
  {
    id: "busbar-engineering",
    name: "Busbar Engineering",
    body: "Current has to be collected and distributed before it can do useful work. Busbar geometry, material and placement are engineered with the conductor architecture, not after it.",
    bullets: [
      "Collection geometry matched to conductor architecture",
      "Current density and distribution",
      "Low-profile, realistically proportioned construction",
      "Termination and joint controls"
    ]
  },
  {
    id: "electrical-exit-leads",
    name: "Electrical Exit Leads",
    body: "The exit is where laminate architecture, electrical function and assembly all meet. HLG engineers lead routing, edge transitions and exit locations around the final construction.",
    bullets: [
      "Exit location engineered with the frame and assembly",
      "Lead routing inside the stack",
      "Edge transitions and sealing considerations",
      "Connector interface definition"
    ]
  }
];
var markets = [
  {
    slug: "aerospace",
    name: "Aerospace",
    blurb: "Heated transparencies with integrated temperature sensing, engineered as one electrothermal system.",
    bullets: [
      "Heated transparencies",
      "RTD sensor mats",
      "Matched heater + sensor systems",
      "Electrical exits",
      "High-power-density applications",
      "Optical performance under electrical load"
    ],
    seoTitle: "Aerospace Functional Interlayers \u2014 Heated & RTD Sensing | HLG",
    seoDescription: "HLG engineers aerospace functional interlayers: electrically heated interlayers, embedded RTD sensor mats, matched heater + sensor systems, electrical exits and validation."
  },
  {
    slug: "defense",
    name: "Defense",
    blurb: "Heated vehicle transparencies and specialty electrical architectures for demanding environments.",
    bullets: [
      "Heated vehicle transparencies",
      "De-ice / defog systems",
      "EMI/RFI integration",
      "Specialty electrical architectures"
    ],
    seoTitle: "Defense Heated & Shielded Functional Interlayers | HLG",
    seoDescription: "HLG engineers functional interlayers for defense glazing: heated vehicle transparencies, de-ice and defog systems, EMI/RFI integration and specialty electrical architectures."
  },
  {
    slug: "automotive",
    name: "Automotive",
    blurb: "Fine-wire heating, localized sensor and camera heating, and embedded antenna architectures.",
    bullets: [
      "Heated windshields",
      "Wiper-park heating",
      "Camera / sensor heating",
      "Embedded antennas",
      "Fine-wire systems"
    ],
    seoTitle: "Automotive Heated Windshield & Antenna Interlayers | HLG",
    seoDescription: "HLG engineers automotive functional interlayers: heated windshields, wiper-park heating, camera and sensor heating zones, embedded antennas and fine-wire systems."
  },
  {
    slug: "rail-transportation",
    name: "Rail & Transportation",
    blurb: "Operator visibility in weather, with heating engineered for large-format transparencies.",
    bullets: [
      "Heated windshields",
      "Operator visibility",
      "De-ice / defog systems",
      "Specialty functional glazing"
    ],
    seoTitle: "Rail & Transit Heated Windshield Interlayers | HLG",
    seoDescription: "HLG engineers heated interlayers for rail and transit transparencies \u2014 operator visibility, de-ice and defog systems, and specialty functional glazing."
  },
  {
    slug: "off-road-commercial-equipment",
    name: "Off-Road & Commercial Equipment",
    blurb: "Cold-weather visibility for equipment cabs, including localized heated zones.",
    bullets: [
      "Windshield heating",
      "Wiper-park heating",
      "Localized heated zones",
      "Cold-weather visibility"
    ],
    seoTitle: "Off-Road & Commercial Equipment Heated Glazing | HLG",
    seoDescription: "HLG engineers heated interlayers for off-road and commercial equipment cabs: windshield heating, wiper-park heating and localized heated zones for cold-weather visibility."
  },
  {
    slug: "architectural-smart-glass",
    name: "Architectural & Smart Glass",
    blurb: "Shielding, transparent conduction and switchable glazing for specialty building envelopes.",
    bullets: [
      "EMI/RFI shielding",
      "Transparent conductors",
      "PDLC integration",
      "Electrically heated glazing",
      "Specialty functional laminates"
    ],
    seoTitle: "Architectural & Smart Glass Functional Interlayers | HLG",
    seoDescription: "HLG engineers architectural functional interlayers: EMI/RFI shielding, transparent conductors, PDLC integration, electrically heated glazing and specialty functional laminates."
  }
];
var libraryTopics = [
  "Heated interlayer engineering",
  "Embedded RTD sensing",
  "Power density",
  "Busbar engineering",
  "Electrical exits",
  "Transparent conductors",
  "EMI/RFI shielding",
  "Antenna integration",
  "PDLC",
  "Sensor heating",
  "Wiper-park heating",
  "Optical performance",
  "Validation"
];

// src/lib/mcp/tools/list-technologies.ts
var list_technologies_default = defineTool({
  name: "list_technologies",
  title: "List HLG technologies",
  description: "List the six electrical functions HLG engineers into laminated glass \u2014 HEAT (electrically heated interlayers), SENSE (embedded RTD temperature sensing), SHIELD (EMI/RFI shielding), CONDUCT (transparent conductors), SWITCH (switchable smart glazing), CONNECT (integrated antennas). Returns slug, headline, lead copy, validated spec ranges, and page path for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = technologies.map((t) => ({
      code: t.code,
      slug: t.slug,
      name: t.name,
      cardCopy: t.cardCopy,
      h1: t.h1,
      lead: t.lead,
      specs: t.specs ?? [],
      sitePath: `/technologies/${t.slug}`
    }));
    return {
      content: [
        {
          type: "text",
          text: items.map(
            (t) => `${t.code} \u2014 ${t.name} [${t.slug}]
${t.cardCopy}
Page: ${t.sitePath}` + (t.specs.length ? `
Specs: ${t.specs.map((s) => `${s.label}: ${s.value}`).join("; ")}` : "")
          ).join("\n\n")
        }
      ],
      structuredContent: { count: items.length, technologies: items }
    };
  }
});

// src/lib/mcp/tools/get-technology.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var get_technology_default = defineTool2({
  name: "get_technology",
  title: "Get technology detail",
  description: "Retrieve the full public engineering description for one HLG technology function by slug or code \u2014 e.g. 'electrically-heated-interlayers' or 'HEAT', 'embedded-temperature-sensing' or 'SENSE'. Returns headline, lead, all page sections with bullets, validated spec ranges, closing position, and the engineering-review CTA.",
  inputSchema: {
    slug: z.string().trim().min(1).describe(
      "Technology slug or code, e.g. 'electrically-heated-interlayers', 'HEAT', 'embedded-temperature-sensing', 'SENSE'."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const needle = slug.toLowerCase().replace(/\s+/g, "");
    const tech = getTech(needle) ?? technologies.find(
      (t) => t.slug.toLowerCase() === needle || t.code.toLowerCase() === needle || t.name.toLowerCase().replace(/\s+/g, "").includes(needle)
    );
    if (!tech) {
      const known = technologies.map((t) => `${t.code} [${t.slug}]`).join(", ");
      throw new ToolError(`No technology matching "${slug}". Known: ${known}`);
    }
    const payload = {
      code: tech.code,
      slug: tech.slug,
      name: tech.name,
      h1: tech.h1,
      lead: tech.lead,
      sections: tech.sections,
      specs: tech.specs ?? [],
      closing: tech.closing ?? null,
      cta: tech.cta ?? null,
      sitePath: `/technologies/${tech.slug}`
    };
    return {
      content: [
        {
          type: "text",
          text: `${payload.code} \u2014 ${payload.name}
${payload.h1}

${payload.lead}

` + payload.sections.map(
            (s) => `## ${s.title}` + (s.body ? `
${s.body}` : "") + (s.bullets?.length ? `
- ${s.bullets.join("\n- ")}` : "")
          ).join("\n\n") + (payload.specs.length ? `

Specs:
${payload.specs.map((s) => `- ${s.label}: ${s.value}`).join("\n")}` : "") + (payload.closing ? `

${payload.closing}` : "")
        }
      ],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-technical-library.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_technical_library_default = defineTool3({
  name: "search_technical_library",
  title: "Search technical library",
  description: "Search the HLG Technical Library coverage by keyword. The V1 library is a framework: HLG maintains an expanding library of engineering resources covering the design and integration of electrical functionality into laminated glass, and technical papers and application notes are coming soon. Returns matching resource topics; no papers are published yet.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Keyword matched against resource topics, e.g. 'busbar', 'RTD', 'EMI'. Omit to list all topics.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.toLowerCase() ?? "";
    const matches = libraryTopics.filter((t) => !q || t.toLowerCase().includes(q));
    const status = "TECHNICAL PAPERS AND APPLICATION NOTES COMING SOON \u2014 the V1 Technical Library is framework only; no papers are published yet.";
    const text = (matches.length ? `HLG Technical Library \u2014 resource topics${query ? ` matching "${query}"` : ""}:
` + matches.map((t) => `- ${t}`).join("\n") : `No library topics matching "${query}".`) + `

${status}
Full topic list:
${libraryTopics.map((t) => `- ${t}`).join("\n")}`;
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        status: "coming-soon",
        query: query ?? null,
        matches,
        allTopics: libraryTopics
      }
    };
  }
});

// src/lib/mcp/tools/get-application-mapping.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_application_mapping_default = defineTool4({
  name: "get_application_mapping",
  title: "Get application mapping",
  description: "Check how HLG markets (Aerospace, Defense, Automotive, Rail & Transportation, Off-Road & Commercial Equipment, Architectural & Smart Glass), integration solutions, and the six technology functions (HEAT, SENSE, SHIELD, CONDUCT, SWITCH, CONNECT) map to each other. Filter by market slug or technology slug/code.",
  inputSchema: {
    market: z3.string().trim().optional().describe("Market slug or name fragment, e.g. 'aerospace', 'rail'. Omit for all markets."),
    technology: z3.string().trim().optional().describe("Technology slug or code fragment, e.g. 'HEAT', 'electrically-heated-interlayers'. Omit for all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ market, technology }) => {
    const m = market?.toLowerCase();
    const t = technology?.toLowerCase();
    const matchedMarkets = markets.filter(
      (x) => !m || x.slug.toLowerCase().includes(m) || x.name.toLowerCase().includes(m)
    );
    const matchedTech = technologies.filter(
      (x) => !t || x.slug.toLowerCase().includes(t) || x.code.toLowerCase().includes(t) || x.name.toLowerCase().includes(t)
    );
    const payload = {
      markets: matchedMarkets.map((x) => ({
        slug: x.slug,
        name: x.name,
        blurb: x.blurb,
        requirements: x.bullets,
        sitePath: x.slug === "aerospace" ? "/markets/aerospace" : `/markets?market=${x.slug}`
      })),
      technologies: matchedTech.map((x) => ({
        code: x.code,
        slug: x.slug,
        name: x.name,
        lead: x.lead,
        sitePath: `/technologies/${x.slug}`
      })),
      solutions: solutions.map((s) => ({
        id: s.id,
        name: s.name,
        body: s.body,
        bullets: s.bullets
      }))
    };
    return {
      content: [
        {
          type: "text",
          text: `Markets (${payload.markets.length}):
` + payload.markets.map((x) => `- ${x.name} [${x.slug}] \u2014 ${x.blurb}`).join("\n") + `

Technologies (${payload.technologies.length}):
` + payload.technologies.map((x) => `- ${x.code} \u2014 ${x.name} [${x.slug}]`).join("\n") + `

Integration solutions (${payload.solutions.length}):
` + payload.solutions.map((s) => `- ${s.name} \u2014 ${s.body}`).join("\n")
        }
      ],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hlg-functional-interlayers",
  title: "Hotlineglass USA \u2014 Functional Interlayers",
  version: "1.0.0",
  instructions: "Public tools for Hotlineglass USA (HLG), a U.S. manufacturer of engineered functional interlayers for laminated glass. Use `list_technologies` for the six electrical functions HLG integrates (HEAT, SENSE, SHIELD, CONDUCT, SWITCH, CONNECT), `get_technology` for full detail on one function, `search_technical_library` for engineering-resource topic coverage (papers coming soon), and `get_application_mapping` to see how markets and integration solutions map to the six functions. All data is public website content.",
  tools: [list_technologies_default, get_technology_default, search_technical_library_default, get_application_mapping_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
